weather:
    key: Replace-This-STring-WIth-KEY
    latitude: 6.6018
    longitude: 3.3520
    units: ca
quote:
    url: http://www.brainyquote.com/quotes_of_the_day.html
fact:
    url: http://www.factretriever.com/
